"""
NetSignal — TraCI Control Loop
================================
This is the heart of the simulation pipeline.

What this script does:
  1. Launches SUMO (GUI or headless) automatically
  2. Connects via TraCI every simulation step
  3. Reads full network state (queue, speed, waiting) for all 36 intersections
  4. Detects emergency vehicles by ID prefix
  5. Runs Dijkstra to compute EV corridor and preempts signals
  6. Logs all state data to CSV for BiLSTM training later
  7. Prints a live dashboard to the console
  8. Saves a summary plot at the end

How to run:
  # GUI mode (watch the simulation):
  python scripts/traciloop.py --gui

  # Headless mode (fast, for training):
  python scripts/traciloop.py

  # Inject an incident at a specific time:
  python scripts/traciloop.py --incident --incident-time 600 --incident-lane e_2_2_2_3_0

Requirements:
  pip install traci numpy pandas matplotlib networkx
  SUMO must be installed and on your PATH (sumo / sumo-gui commands work)
"""

import os
import sys
import csv
import time
import argparse
import subprocess
import signal
import random
from pathlib import Path
from collections import defaultdict
from datetime import datetime

import numpy as np
import networkx as nx

# ──────────────────────────────────────────────
# Attempt to import traci. Give helpful error if not installed.
# ──────────────────────────────────────────────
try:
    import traci
    import traci.constants as tc
except ImportError:
    print("ERROR: traci is not installed.")
    print("Run:  pip install traci eclipse-sumo")
    sys.exit(1)


# ══════════════════════════════════════════════════════════
#   CONFIGURATION
# ══════════════════════════════════════════════════════════

# Path resolution — works regardless of where you run the script from
SCRIPT_DIR   = Path(__file__).parent.resolve()
PROJECT_DIR  = SCRIPT_DIR.parent
CONFIG_FILE  = PROJECT_DIR / "config" / "netsignal.sumocfg"
OUTPUT_DIR   = PROJECT_DIR / "output"
OUTPUT_DIR.mkdir(exist_ok=True)

TRACI_PORT   = 8813
STEP_LENGTH  = 1       # seconds per simulation step (matches sumocfg)
SIM_DURATION = 3600    # total simulation steps
CONTROL_FREQ = 5       # run signal control logic every N steps (5s cycle)
EV_PREFIX    = "EV_"   # vehicle IDs starting with this are emergency vehicles
# Node IDs loaded from config/grid_nodes.txt (generated by fix_flows.py)
def _load_node_map():
    from pathlib import Path
    cfg = Path(__file__).parent.parent / "config" / "grid_nodes.txt"
    m = {}
    if cfg.exists():
        for line in cfg.read_text().splitlines():
            if line.startswith("#") or "=" not in line:
                continue
            k, v = line.strip().split("=", 1)
            m[k] = v
    return m

_node_map = _load_node_map()
HOSPITAL_NODE = _node_map.get("HOSPITAL_NODE", "D3")  # D3 = col3/row3 in netgenerate A-F naming

# Phase indices (standard 4-phase intersection):
#   Phase 0: EW green (East-West traffic moves)
#   Phase 1: EW yellow
#   Phase 2: NS green (North-South traffic moves)
#   Phase 3: NS yellow
PHASE_EW_GREEN = 0
PHASE_EW_YELLOW = 1
PHASE_NS_GREEN = 2
PHASE_NS_YELLOW = 3

# Load actual node IDs from grid_nodes.txt (written by fix_flows.py)
GRID_SIZE = 6

ALL_INTERSECTIONS = [_node_map.get(f"NODE_{c}_{r}", f"{c}/{r}")
                     for r in range(GRID_SIZE) for c in range(GRID_SIZE)]
ALL_INTERSECTIONS = [n for n in ALL_INTERSECTIONS if n]  # filter blanks

# Fixed-time cycle for baseline (used when no ML model is active)
DEFAULT_GREEN_DURATION = 30   # seconds
DEFAULT_YELLOW_DURATION = 3   # seconds


# ══════════════════════════════════════════════════════════
#   ROAD GRAPH (for Dijkstra EV routing)
# ══════════════════════════════════════════════════════════

def build_road_graph():
    """
    Build a NetworkX directed graph of the 6x6 grid.
    Nodes = intersections (n_r_c)
    Edges = road segments with weight = length (300m each)

    This graph is used for Dijkstra path finding when an
    emergency vehicle is detected.
    """
    G = nx.DiGraph()

    for r in range(GRID_SIZE):
        for c in range(GRID_SIZE):
            G.add_node(f"{c}/{r}", pos=(c * 300, r * 300))

    # Add edges for every adjacent pair (horizontal and vertical)
    for r in range(GRID_SIZE):
        for c in range(GRID_SIZE - 1):
            # Horizontal bidirectional
            G.add_edge(f"{c}/{r}",   f"{c+1}/{r}", weight=300, edge_id=f"{c}/{r}-{c+1}/{r}")
            G.add_edge(f"{c+1}/{r}", f"{c}/{r}",   weight=300, edge_id=f"{c+1}/{r}-{c}/{r}")

    for r in range(GRID_SIZE - 1):
        for c in range(GRID_SIZE):
            # Vertical bidirectional
            G.add_edge(f"{c}/{r}",   f"{c}/{r+1}", weight=300, edge_id=f"{c}/{r}-{c}/{r+1}")
            G.add_edge(f"{c}/{r+1}", f"{c}/{r}",   weight=300, edge_id=f"{c}/{r+1}-{c}/{r}")

    return G


# ══════════════════════════════════════════════════════════
#   STATE READER
# ══════════════════════════════════════════════════════════

def read_network_state():
    """
    Read the full network state from SUMO via TraCI.

    Returns a dict keyed by intersection ID containing:
      - lanes         : list of lane IDs approaching this intersection
      - waiting       : total waiting vehicles (speed < 0.1 m/s)
      - queue         : total queued vehicles
      - avg_speed     : mean speed across all approaching lanes (m/s)
      - vehicle_count : total vehicles on approaching lanes
      - current_phase : active signal phase index

    Also returns:
      - emergency_vehicles : dict { veh_id -> lane_id } for any EV_ vehicles
      - total_waiting      : sum of waiting vehicles across all intersections
    """
    state = {}
    emergency_vehicles = {}
    total_waiting = 0

    # Get all vehicle speeds and positions in one call (efficient)
    try:
        all_lane_vehicles = traci.lane.getAllSubscriptionResults()
    except Exception:
        all_lane_vehicles = {}

    for node_id in ALL_INTERSECTIONS:
        try:
            # Get all incoming lanes for this intersection
            incoming_lanes = traci.junction.getContextSubscriptionResults(node_id)

            # Fallback: get lanes from the trafficlight
            lane_ids = traci.trafficlight.getControlledLanes(node_id)
            lane_ids = list(set(lane_ids))  # deduplicate

            waiting_count  = 0
            vehicle_count  = 0
            speed_sum      = 0.0
            speed_readings = 0

            for lane_id in lane_ids:
                try:
                    waiting  = traci.lane.getLastStepHaltingNumber(lane_id)
                    vehicles = traci.lane.getLastStepVehicleNumber(lane_id)
                    speed    = traci.lane.getLastStepMeanSpeed(lane_id)

                    waiting_count  += waiting
                    vehicle_count  += vehicles
                    speed_sum      += speed
                    speed_readings += 1

                    # Check each vehicle on this lane for EV prefix
                    veh_ids = traci.lane.getLastStepVehicleIDs(lane_id)
                    for vid in veh_ids:
                        if vid.startswith(EV_PREFIX):
                            emergency_vehicles[vid] = lane_id

                except traci.exceptions.TraCIException:
                    pass  # Lane may not exist yet — ignore

            avg_speed = speed_sum / speed_readings if speed_readings > 0 else 0.0

            try:
                current_phase = traci.trafficlight.getPhase(node_id)
            except Exception:
                current_phase = -1

            state[node_id] = {
                "lanes":         lane_ids,
                "waiting":       waiting_count,
                "queue":         waiting_count,  # proxy — refine later with actual queue length
                "avg_speed":     round(avg_speed, 3),
                "vehicle_count": vehicle_count,
                "current_phase": current_phase,
            }

            total_waiting += waiting_count

        except traci.exceptions.TraCIException:
            state[node_id] = {
                "lanes": [], "waiting": 0, "queue": 0,
                "avg_speed": 0.0, "vehicle_count": 0, "current_phase": -1
            }

    return state, emergency_vehicles, total_waiting


# ══════════════════════════════════════════════════════════
#   FIXED-TIME CONTROLLER (baseline)
# ══════════════════════════════════════════════════════════

class FixedTimeController:
    """
    Simple fixed-time signal controller.
    All intersections cycle through EW-green → EW-yellow → NS-green → NS-yellow
    on a fixed schedule.

    This is your baseline. Your GNN will replace this class.
    """
    def __init__(self, green_duration=30, yellow_duration=3):
        self.green_dur  = green_duration
        self.yellow_dur = yellow_duration
        self.cycle_len  = 2 * (green_duration + yellow_duration)
        self.step       = 0

    def get_actions(self, state):
        """Returns {intersection_id: phase_index} for all intersections."""
        actions = {}
        offset = 0
        for node_id in ALL_INTERSECTIONS:
            # Stagger intersections by a small offset to avoid all switching at once
            cycle_pos = (self.step + offset) % self.cycle_len
            if   cycle_pos < self.green_dur:
                phase = PHASE_EW_GREEN
            elif cycle_pos < self.green_dur + self.yellow_dur:
                phase = PHASE_EW_YELLOW
            elif cycle_pos < 2 * self.green_dur + self.yellow_dur:
                phase = PHASE_NS_GREEN
            else:
                phase = PHASE_NS_YELLOW
            actions[node_id] = phase
            offset = (offset + 2) % 8  # small stagger per intersection
        self.step += 1
        return actions


# ══════════════════════════════════════════════════════════
#   EMERGENCY VEHICLE PREEMPTION
# ══════════════════════════════════════════════════════════

class EVPreemptor:
    """
    When an emergency vehicle is detected, computes the shortest path
    from its current position to the hospital node and preempts all
    intersections along that path with a green phase toward the EV.

    Uses NetworkX Dijkstra on the road graph.
    """
    def __init__(self, road_graph):
        self.graph   = road_graph
        self.active  = False
        self.path    = []
        self.ev_id   = None

    def update(self, emergency_vehicles):
        """
        Called each control cycle with the dict of detected EVs.
        Updates the preemption path if an EV is present.
        """
        if not emergency_vehicles:
            if self.active:
                print("\n  ✓ EV has cleared the network — releasing preemption")
            self.active = False
            self.path   = []
            self.ev_id  = None
            return

        # Take the first EV found (extend later for multi-EV)
        ev_id, current_lane = next(iter(emergency_vehicles.items()))

        if ev_id != self.ev_id:
            self.ev_id = ev_id
            print(f"\n  🚨 EMERGENCY VEHICLE DETECTED: {ev_id}")
            print(f"     Current lane: {current_lane}")

        # Convert lane ID to node ID
        # Lane format: e_{r1}_{c1}_{r2}_{c2}_{lane_index}
        # → source node = n_{r1}_{c1}
        current_node = self._lane_to_node(current_lane, ev_id)
        if current_node is None:
            return

        try:
            path = nx.dijkstra_path(self.graph, source=current_node, target=HOSPITAL_NODE)
            self.path   = path
            self.active = True
            print(f"     Preemption corridor: {' → '.join(path)}")
        except nx.NetworkXNoPath:
            print(f"     WARNING: No path from {current_node} to {HOSPITAL_NODE}")
            self.active = False

    def _lane_to_node(self, lane_id, ev_id):
        """
        Extract source node from a lane/edge ID.
        netgenerate edge format: "A0-B0" (fromNode-toNode)
        Lane format: "A0-B0_0" (edge_id + _lane_index)
        Source node: part before first '-' e.g. "A0"
        """
        try:
            road_id = traci.vehicle.getRoadID(ev_id)
            if road_id and not road_id.startswith(":") and "-" in road_id:
                return road_id.split("-")[0]
        except Exception:
            pass

        # Fallback: parse from lane_id
        if lane_id and "-" in lane_id:
            edge_id = lane_id.rsplit("_", 1)[0]  # strip lane index
            return edge_id.split("-")[0]

        return None

    def get_preempted_intersections(self):
        """Returns the set of intersection IDs that should be preempted."""
        return set(self.path) if self.active else set()

    def get_phase_for_intersection(self, node_id):
        """
        Returns the phase index that gives green in the direction of EV travel.
        Determines direction by checking this node's position in the path.
        """
        if node_id not in self.path:
            return None

        idx = self.path.index(node_id)
        if idx >= len(self.path) - 1:
            return PHASE_NS_GREEN  # Last node — default

        current = node_id
        next_nd = self.path[idx + 1]

        # Parse col/row from node IDs using reverse lookup of _node_map
        rev = {v: (int(k.split("_")[1]), int(k.split("_")[2]))
               for k, v in _node_map.items() if k.startswith("NODE_")}
        c1, r1 = rev.get(current, (0, 0))
        c2, r2 = rev.get(next_nd,  (0, 0))

        # EV moving horizontally → give EW green
        if r1 == r2:
            return PHASE_EW_GREEN
        # EV moving vertically → give NS green
        else:
            return PHASE_NS_GREEN


# ══════════════════════════════════════════════════════════
#   INCIDENT INJECTOR
# ══════════════════════════════════════════════════════════

class IncidentInjector:
    """
    Injects simulated traffic incidents by stopping vehicles on a target lane.
    Used to generate labelled training data for the BiLSTM incident detector.

    An incident is represented as:
      - A target lane where vehicles are stopped (speed = 0)
      - A start time and (optional) end time
    """
    def __init__(self, target_lane, start_time, end_time=None, label="blockage"):
        self.target_lane = target_lane
        self.start_time  = start_time
        self.end_time    = end_time if end_time else start_time + 300  # 5 min default
        self.label       = label
        self.active      = False
        self.affected_vehicles = set()

    def step(self, sim_time):
        """Called every simulation step. Returns True if incident is currently active."""
        if sim_time >= self.start_time and sim_time <= self.end_time:
            if not self.active:
                print(f"\n  💥 INCIDENT INJECTED at t={sim_time}s | Lane: {self.target_lane}")
                self.active = True

            # Stop all vehicles on the target lane
            try:
                veh_ids = traci.lane.getLastStepVehicleIDs(self.target_lane)
                for vid in veh_ids:
                    if vid not in self.affected_vehicles:
                        try:
                            traci.vehicle.setSpeed(vid, 0.0)
                            self.affected_vehicles.add(vid)
                        except traci.exceptions.TraCIException:
                            pass
            except traci.exceptions.TraCIException:
                pass

            return True

        elif self.active and sim_time > self.end_time:
            # Release stopped vehicles
            print(f"\n  ✓ Incident cleared at t={sim_time}s")
            for vid in self.affected_vehicles:
                try:
                    traci.vehicle.setSpeed(vid, -1)  # -1 = restore normal speed
                except Exception:
                    pass
            self.affected_vehicles.clear()
            self.active = False

        return False


# ══════════════════════════════════════════════════════════
#   DATA LOGGER
# ══════════════════════════════════════════════════════════

class DataLogger:
    """
    Logs simulation state every step to CSV files.
    This data is used to train the BiLSTM incident detector.

    Output files:
      output/state_log.csv    — per-intersection state per timestep
      output/metrics_log.csv  — network-wide metrics per timestep
      output/incident_log.csv — ground truth incident labels
    """
    def __init__(self):
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.state_file    = OUTPUT_DIR / f"state_log_{ts}.csv"
        self.metrics_file  = OUTPUT_DIR / f"metrics_log_{ts}.csv"
        self.incident_file = OUTPUT_DIR / f"incident_log_{ts}.csv"

        # Write CSV headers
        with open(self.state_file, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow([
                "timestep", "intersection", "waiting", "queue",
                "avg_speed", "vehicle_count", "current_phase",
                "ev_active", "incident_active"
            ])

        with open(self.metrics_file, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow([
                "timestep", "total_waiting", "total_vehicles",
                "avg_speed_network", "ev_active", "incident_active"
            ])

        with open(self.incident_file, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["timestep", "lane", "label"])

        self.rows_buffered = []
        self.buffer_limit  = 100  # flush every 100 rows

    def log_state(self, timestep, state, ev_active, incident_active):
        with open(self.state_file, "a", newline="") as f:
            writer = csv.writer(f)
            for node_id, s in state.items():
                writer.writerow([
                    timestep, node_id,
                    s["waiting"], s["queue"], s["avg_speed"],
                    s["vehicle_count"], s["current_phase"],
                    int(ev_active), int(incident_active)
                ])

    def log_metrics(self, timestep, total_waiting, state, ev_active, incident_active):
        total_vehicles = sum(s["vehicle_count"] for s in state.values())
        speeds = [s["avg_speed"] for s in state.values() if s["avg_speed"] > 0]
        avg_speed_network = round(np.mean(speeds), 3) if speeds else 0.0

        with open(self.metrics_file, "a", newline="") as f:
            writer = csv.writer(f)
            writer.writerow([
                timestep, total_waiting, total_vehicles,
                avg_speed_network, int(ev_active), int(incident_active)
            ])

    def log_incident(self, timestep, lane, label):
        with open(self.incident_file, "a", newline="") as f:
            writer = csv.writer(f)
            writer.writerow([timestep, lane, label])


# ══════════════════════════════════════════════════════════
#   CONSOLE DASHBOARD
# ══════════════════════════════════════════════════════════

def print_dashboard(step, total_waiting, ev_active, incident_active, ev_path, state):
    """Prints a live status dashboard to the console every control cycle."""

    # Pick a few intersections to display
    sample_nodes = [_node_map.get(f"NODE_{c}_{r}", f"{c}/{r}") for c,r in [(0,0),(2,2),(3,3),(5,5),(3,1)]]

    print(f"\n{'═'*65}")
    print(f"  NetSignal Dashboard  |  Step: {step:>5}s  |  "
          f"{'🟢' if not ev_active else '🔴'} EV: {'ACTIVE' if ev_active else 'clear  '}"
          f"  |  {'⚠️  INCIDENT' if incident_active else '            '}")
    print(f"{'─'*65}")
    print(f"  Network total waiting: {total_waiting:>4} vehicles")

    if ev_active and ev_path:
        print(f"  EV corridor: {' → '.join(ev_path)}")

    print(f"{'─'*65}")
    print(f"  {'Intersection':<12} {'Waiting':>7} {'Vehicles':>8} {'Avg Speed':>10} {'Phase':>6}")
    print(f"  {'─'*12} {'─'*7} {'─'*8} {'─'*10} {'─'*6}")

    for node_id in sample_nodes:
        if node_id in state:
            s = state[node_id]
            phase_labels = {0: "EW 🟢", 1: "EW 🟡", 2: "NS 🟢", 3: "NS 🟡"}
            phase_str = phase_labels.get(s["current_phase"], f"P{s['current_phase']}")
            speed_str = f"{s['avg_speed']:.1f} m/s"
            print(f"  {node_id:<12} {s['waiting']:>7} {s['vehicle_count']:>8} {speed_str:>10} {phase_str:>6}")

    print(f"{'═'*65}")


# ══════════════════════════════════════════════════════════
#   MAIN TRACI LOOP
# ══════════════════════════════════════════════════════════

def run_simulation(gui=True, inject_incident=False, incident_time=600,
                   incident_lane="e_2_2_2_3_0"):
    """
    Main simulation loop.

    Parameters
    ----------
    gui            : bool  — launch sumo-gui (True) or headless sumo (False)
    inject_incident: bool  — inject a simulated incident for training data
    incident_time  : int   — timestep to inject the incident
    incident_lane  : str   — lane ID to block
    """

    # ── 1. Launch SUMO ──
    sumo_binary = "sumo-gui" if gui else "sumo"
    VIEW_FILE = PROJECT_DIR / "config" / "netsignal.view.xml"

    sumo_cmd = [
        sumo_binary,
        "-c", str(CONFIG_FILE),
        # NOTE: --remote-port and --start are handled automatically by traci.start()
        # NOTE: --quit-on-end removed — it conflicts with quit-on-end=false in sumocfg
    ]

    # Pass view settings file for GUI mode (handles viewport, breakpoints etc.)
    if gui and VIEW_FILE.exists():
        sumo_cmd += ["-g", str(VIEW_FILE)]

    # Always suppress route errors at command level too (belt-and-suspenders)
    sumo_cmd += ["--ignore-route-errors"]
    if not gui:
        sumo_cmd += ["--no-step-log", "--no-warnings"]

    print(f"\n{'═'*65}")
    print(f"  NetSignal Traffic Simulation Starting")
    print(f"{'─'*65}")
    print(f"  Mode       : {'GUI (sumo-gui)' if gui else 'Headless (sumo)'}")
    print(f"  Config     : {CONFIG_FILE}")
    print(f"  Duration   : {SIM_DURATION}s (1 hour)")
    print(f"  Control    : Fixed-time baseline (replace with GNN later)")
    print(f"  Hospital   : {HOSPITAL_NODE}")
    print(f"  EV depart  : t=900s")
    if inject_incident:
        print(f"  Incident   : t={incident_time}s on lane {incident_lane}")
    print(f"{'═'*65}\n")

    # ── 2. Ensure output directory exists before SUMO tries to write to it ──
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # ── 3. Launch SUMO and connect TraCI in one synchronized call ──
    # traci.start() is the recommended approach — it handles process launch,
    # port binding, and connection handshake atomically (no race conditions).
    print(f"  Launching: {' '.join(sumo_cmd)}\n")
    sumo_process = None
    sumo_stderr_lines = []  # traci.start() captures output internally
    try:
        traci.start(sumo_cmd, port=TRACI_PORT)
        print("  ✓ TraCI connected successfully\n")
    except traci.exceptions.FatalTraCIError as e:
        print(f"  ✗ TraCI/SUMO launch failed: {e}")
        print("    Check that SUMO is installed and on your PATH.")
        print("    Download: https://sumo.dlr.de/docs/Downloads.php")
        return
    except FileNotFoundError:
        print(f"  ✗ Could not find '{sumo_binary}'. Is SUMO installed and on your PATH?")
        print("    Download: https://sumo.dlr.de/docs/Downloads.php")
        return
    except Exception as e:
        print(f"  ✗ Failed to start SUMO: {e}")
        return

    # ── 4. Initialise components ──
    road_graph  = build_road_graph()
    controller  = FixedTimeController(DEFAULT_GREEN_DURATION, DEFAULT_YELLOW_DURATION)
    preemptor   = EVPreemptor(road_graph)
    logger      = DataLogger()
    incident    = IncidentInjector(incident_lane, incident_time) if inject_incident else None

    # Subscribe all intersections for efficient state reading
    for node_id in ALL_INTERSECTIONS:
        try:
            traci.junction.subscribeContext(
                node_id, tc.CMD_GET_VEHICLE_VARIABLE, 100,
                [tc.VAR_SPEED, tc.VAR_LANE_ID]
            )
        except Exception:
            pass

    # Metrics tracking
    waiting_history = []
    start_wall_time = time.time()

    # ── 5. Main simulation loop ──
    try:
        for step in range(SIM_DURATION):

            # Advance simulation by one step
            try:
                traci.simulationStep()
            except traci.exceptions.FatalTraCIError as e:
                print(f"\n  SUMO disconnected at step {step}: {e}")
                print("  Check the SUMO terminal/window for error details.")
                break

            # Read full network state
            state, emergency_vehicles, total_waiting = read_network_state()
            waiting_history.append(total_waiting)

            ev_active       = len(emergency_vehicles) > 0
            incident_active = incident.step(step) if incident else False

            # Log state every step
            logger.log_state(step, state, ev_active, incident_active)

            # Log incident ground truth
            if incident_active:
                logger.log_incident(step, incident_lane, "blockage")

            # ── Control logic every CONTROL_FREQ steps ──
            if step % CONTROL_FREQ == 0:

                # Update EV preemptor
                preemptor.update(emergency_vehicles)

                # Get fixed-time actions (placeholder for GNN)
                actions = controller.get_actions(state)

                # Override preempted intersections
                preempted = preemptor.get_preempted_intersections()
                for node_id in preempted:
                    ev_phase = preemptor.get_phase_for_intersection(node_id)
                    if ev_phase is not None:
                        actions[node_id] = ev_phase

                # Apply all phase actions to SUMO
                for node_id, phase in actions.items():
                    try:
                        current = traci.trafficlight.getPhase(node_id)
                        # Only change if different and not mid-yellow
                        if current != phase and current not in [PHASE_EW_YELLOW, PHASE_NS_YELLOW]:
                            traci.trafficlight.setPhase(node_id, phase)
                    except traci.exceptions.TraCIException:
                        pass

                # Log network metrics
                logger.log_metrics(step, total_waiting, state, ev_active, incident_active)

                # Print dashboard every 30 steps (every 30 seconds sim time)
                if step % 30 == 0:
                    print_dashboard(
                        step, total_waiting, ev_active, incident_active,
                        preemptor.path, state
                    )

    except KeyboardInterrupt:
        print("\n\n  Simulation interrupted by user.")

    finally:
        # ── 6. Cleanup ──
        wall_time = time.time() - start_wall_time
        print(f"\n{'═'*65}")
        print(f"  Simulation Complete")
        print(f"{'─'*65}")
        print(f"  Sim time       : {SIM_DURATION}s")
        rt = f"{SIM_DURATION/wall_time:.1f}x" if wall_time > 0.01 else "N/A"
        print(f"  Wall time      : {wall_time:.1f}s ({rt} real-time)")
        if waiting_history:
            print(f"  Avg waiting    : {np.mean(waiting_history):.1f} vehicles")
            print(f"  Peak waiting   : {max(waiting_history)} vehicles")
        else:
            print("  Avg waiting    : N/A (simulation did not run)")
            print("  Peak waiting   : N/A")
        print(f"  Data logged to : {OUTPUT_DIR}")
        print(f"{'═'*65}\n")

        try:
            traci.close()
        except Exception:
            pass
        # Note: when using traci.start(), SUMO process is managed by traci internally

        # Save summary plot
        if waiting_history:
            _save_summary_plot(waiting_history, inject_incident, incident_time)


# ══════════════════════════════════════════════════════════
#   SUMMARY PLOT
# ══════════════════════════════════════════════════════════

def _save_summary_plot(waiting_history, incident_injected, incident_time):
    """Saves a waiting time plot to output/summary_plot.png"""
    try:
        import matplotlib
        matplotlib.use("Agg")  # Non-interactive backend
        import matplotlib.pyplot as plt
        import matplotlib.patches as mpatches

        fig, ax = plt.subplots(figsize=(14, 5))
        timesteps = list(range(len(waiting_history)))

        ax.fill_between(timesteps, waiting_history, alpha=0.2, color="#2E75B6")
        ax.plot(timesteps, waiting_history, color="#2E75B6", linewidth=1.5,
                label="Network waiting vehicles")

        # Mark EV event
        if 900 < len(waiting_history):
            ax.axvline(x=900, color="red", linestyle="--", linewidth=1.5, alpha=0.8)
            ax.text(910, max(waiting_history) * 0.9, "EV dispatched",
                    color="red", fontsize=9)

        # Mark incident
        if incident_injected and incident_time < len(waiting_history):
            ax.axvline(x=incident_time, color="orange", linestyle="--",
                       linewidth=1.5, alpha=0.8)
            ax.text(incident_time + 10, max(waiting_history) * 0.7, "Incident injected",
                    color="orange", fontsize=9)

        # Rolling average
        window = 30
        if len(waiting_history) > window:
            rolling = np.convolve(waiting_history, np.ones(window)/window, mode='valid')
            ax.plot(range(window-1, len(waiting_history)), rolling,
                    color="#C00000", linewidth=2, linestyle="-",
                    label=f"{window}s rolling average")

        ax.set_xlabel("Simulation Time (seconds)", fontsize=11)
        ax.set_ylabel("Total Waiting Vehicles", fontsize=11)
        ax.set_title("NetSignal — Network Waiting Vehicles Over Time\n"
                     "(Fixed-time baseline — replace with GNN for improvement)",
                     fontsize=12, fontweight="bold")
        ax.legend(fontsize=10)
        ax.grid(True, alpha=0.3)
        ax.set_xlim(0, len(waiting_history))
        ax.set_ylim(0, max(waiting_history) * 1.15 if waiting_history else 10)

        # Annotate stats
        stats_text = (
            f"Avg: {np.mean(waiting_history):.1f}  |  "
            f"Peak: {max(waiting_history)}  |  "
            f"Final: {waiting_history[-1]}"
        )
        ax.text(0.99, 0.02, stats_text, transform=ax.transAxes,
                fontsize=9, ha="right", color="#404040",
                bbox=dict(boxstyle="round,pad=0.3", facecolor="white", alpha=0.8))

        plt.tight_layout()
        out_path = OUTPUT_DIR / "summary_plot.png"
        plt.savefig(out_path, dpi=150, bbox_inches="tight")
        plt.close()
        print(f"  Plot saved: {out_path}")

    except ImportError:
        print("  (matplotlib not installed — skipping plot)")
    except Exception as e:
        print(f"  (Plot generation failed: {e})")


# ══════════════════════════════════════════════════════════
#   ENTRY POINT
# ══════════════════════════════════════════════════════════

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="NetSignal TraCI Simulation Loop",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python traciloop.py                     # Headless (fast)
  python traciloop.py --gui               # GUI mode (watch the sim)
  python traciloop.py --gui --incident    # GUI + inject incident at t=600s
  python traciloop.py --incident --incident-time 300 --incident-lane e_1_2_1_3_0
        """
    )

    parser.add_argument(
        "--gui", action="store_true", default=False,
        help="Launch sumo-gui for visualisation (default: headless)"
    )
    parser.add_argument(
        "--incident", action="store_true", default=False,
        help="Inject a simulated traffic incident"
    )
    parser.add_argument(
        "--incident-time", type=int, default=600,
        help="Simulation timestep to inject the incident (default: 600)"
    )
    parser.add_argument(
        "--incident-lane", type=str, default="e_2_2_2_3_0",
        help="Lane ID to block during incident (default: e_2_2_2_3_0)"
    )

    args = parser.parse_args()

    run_simulation(
        gui=args.gui,
        inject_incident=args.incident,
        incident_time=args.incident_time,
        incident_lane=args.incident_lane
    )